spring :
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
             endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
#      cloud:
#        azure:
#          storage:
#            blob:
#              account-name: ${AZURE_STORAGE_ACCOUNT_NAME} #envionment variable
#              account-key: ${AZURE_STORAGE_ACCOUNT_KEY}   #envionment variable


  datasource:
    url: ${datasource-url} # secret from azure keyvault
    username: ${datasource-username} # secret from azure keyvault
    password: ${datasource-password} # secret from azure keyvault

  jpa:
    hibernate:
      ddl-auto: none




